#ifndef SYNCREQUEST_GLOBAL_H
#define SYNCREQUEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYNCREQUEST_LIBRARY)
#  define SYNCREQUESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYNCREQUESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYNCREQUEST_GLOBAL_H
